name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [8.x, 10.x, 12.x]
        exclude:
        # On Windows, run tests with only the latest environments.
        - os: windows-latest
          node-version: 8.x
        - os: windows-latest
          node-version: 10.x

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and and test
      run: |
        npm install
        npm run test-cov
      env:
        CI: true
        FORCE_COLOR: 2

    - name: Upload coverage to Codecov
        # https://github.com/codecov/codecov-bash/blob/1044b7a243e0ea0c05ed43c2acd8b7bb7cef340c/codecov#L158
      run: npx codecov
        -f "./coverage/coverage-final.json"
        -y "./.codecov.yml"
        -b ${{ github.head_ref }}
        -c ${{ github.event.after }}
